version: '3.8'

services:
  api:
    container_name: lm-api
    image: node:20.10.0-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/app

  worker:
    container_name: lm-worker
    image: node:20.10.0-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn start:dev"
    environment:
      - WORKER=1
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
    ports:
      - 3001:3000
    volumes:
      - .:/app

  mongo:
    container_name: lm-mongo
    image: mongo:7.0.4
    ports:
      - 27017:27017
    volumes:
      - lm.mongo.config:/data/configdb
      - lm.mongo.db:/data/db

  redis:
    container_name: lm-redis
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379

volumes:
  lm.mongo.config:
    driver: local
  lm.mongo.db:
    driver: local
